apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    tier: front-end
spec:
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      labels:
        tier: front-end
    spec:
      containers:
      - name: my-app
        image: httpd:2-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
